# Generated by Django 4.2.5 on 2023-09-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='eventfollower',
            name='follower',
        ),
    ]
